apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_SERVICE_NAME} #Service 的名称
  namespace: ${K8S_DEPLOY_NAMESPACE}
  labels: #Service 自己的标签
    appname: ${SERVICE_SERVICE_NAME} #为该 Service 设置 key 为 appname，value 为SERVICE_SERVICE_NAME 的标签
spec: #这是关于该 Service 的定义，描述了 Service 如何选择 Pod，如何被访问
  selector: #标签选择器
    appname: ${SERVICE_NAME} #选择包含标签 appname 的 Pod
  ports:
  - name: ${SERVICE_SERVICE_PORT_NAME} #端口的名字
    protocol: TCP #协议类型 TCP/UDP
    port: 32610 #集群内的其他容器组可通过 32610 端口访问 Service
    nodePort: ${SERVICE_SERVICE_NODE_PORT} #通过任意节点的 SERVICE_SERVICE_NODE_PORT 端口访问 Service
    targetPort: 8100 #将请求转发到匹配 Pod 的 32610 端口
  type: NodePort #Serive的类型，ClusterIP/NodePort/LoaderBalancer